### ISSUE TITLE
legyen, kérlek, a CODΞ felirat mindenhol ilyen 

### ISSUE THREAD

**Issue by thebalazs** [THE-SOURCE-CODE-AGENCY/Candidate-Lookup-by-CODE#11]
![Screenshot 2022-09-12 at 18 19 09](https://user-images.githubusercontent.com/33448047/189705636-ea320473-b3cb-413c-b78a-b57aa8dc5a6d.png)

**Comment by GuBee33** [comment]
Sajnos nem szerette azt betutipust de majd még küzdök vele

**Comment by GuBee33** [comment]
na most utána néztem mi a baj. a menüben (jobb click) sikerült orvosolni viszont az ablak titlejében nem és úgy fest nem is fog
"This is a font problem rather than an encoding problem; a small rectangle in place of a character typically means that the character is not present in the font(s) used.

Browsers typically use some specific fonts when they render title element contents (somewhere outside the page itself). These fonts may depend on the settings in the operating systems. On Windows 7 for example, the default for them is 9pt Segoe UI, a relatively rich font, whereas older systems have more limited fonts. Anyway, that’s outside an author’s hands.

So the conclusion is that special symbols should be avoided in title elements. Their rendering is not guaranteed, and they probably have no value as far as search engines are considered."

**Comment by GuBee33** [comment]
valami javaslat alternatív szövegnek? (pls Let's find your candidate)

**Comment by thebalazs** [comment]
Candidate Lookup by CODE helyett? nem, jó ez így akkor, sima E-vel :)

**Comment by thebalazs** [comment]
közben rájöttem, hogy ez kétszer van nyitva - bocs! ez is uez: https://github.com/THE-SOURCE-CODE-AGENCY/Candidate-Lookup-by-CODE/issues/13

nézd, itt látszólag sikerült használni ezt az E betűt 

![Screenshot 2022-09-12 at 18 48 49](https://user-images.githubusercontent.com/33448047/189871735-5f3bb35f-8ddb-413a-93b5-4cf5fd8b81e3.png)
